---
title: "Tornado"
output: html_document
date: "2023-05-17"
---

```{r}
library(tidyverse)
library(maps)
library(ggtext)
```


```{r}
tornados <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-16/tornados.csv')
```


```{r}
# add fonts from Google
font_add_google("Inter")
showtext_auto()
```


```{r}
inj_by_state <- tornados %>%
  select(st, inj) %>%
  group_by(st) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

inj_by_state %>%
  ggplot(aes(x=reorder(st, +count), y=count)) +
  geom_bar(stat = "identity") +
  coord_flip()
```


```{r}
inj_avg <- tornados %>%
  group_by(st) %>%
  summarize(avg_inj = mean(inj)) %>%
  ungroup() %>%
  inner_join(tibble(st = state.abb, region = state.name), by = "st") %>%
  inner_join(map_data("state") %>% tibble() %>% mutate(region = str_to_title(region)), by = "region")
```


```{r}
tornado_plot <- inj_avg %>%
  ggplot(aes(x = long, y = lat, group = group, fill = avg_inj)) +
  geom_polygon() +
  coord_map() +
  scale_fill_gradient2(
    high = "#BB650B",
    low = "#559999",
    mid = "grey80",
    midpoint = median(inj_avg$avg_inj)) +
  labs(x = "", y = "", title = "Where do Tornados Hurt the Most?", subtitle = "Average number of injuries caused by tornados by state", caption = "Kyle Torres | Data: NOAA's National Weather Service Storm Prediction Center") +
  #guides(fill=guide_legend(title="Avg num of inj")) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "right",
    plot.title = element_text(colour = "black", face = "bold", 
                                  size = 24, family = "Inter"),
    plot.subtitle = element_text(colour = "black", 
                                  size = 14, family = "Inter")
  )

tornado_plot

ggsave(plot = tornado_plot, file = "Tornado Injuries.jpeg", height = 5.5, width = 9)
```

